import { MetadataRoute } from 'next'
import { SITE_URL } from '@/lib/seo'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/marketplace',
          '/marketplace/',
          '/assistant',
          '/blog',
          '/blog/',
          '/store/',
          '/sellers/',
          '/seller/',
          '/about',
          '/pricing',
          '/help',
          '/trust',
          '/terms',
          '/privacy',
          '/cookies',
          '/refund',
          '/careers',
          '/contact',
          '/press',
          '/community',
          '/partnerships',
          '/status',
          '/auth/login',
          '/auth/sign-up',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/profile/',
          '/seller/new',
          '/seller/edit/',
          '/auth/reset-password',
          '/auth/forgot-password',
          '/auth/callback',
          '/auth/verify',
          '/_next/',
          '/static/',
          '/offline',
          '/payment/',
          '/orders/',
          '/wallet/',
          '/notifications/',
        ],
      },
      { userAgent: 'GPTBot',       disallow: '/' },
      { userAgent: 'ChatGPT-User', disallow: '/' },
      { userAgent: 'CCBot',        disallow: '/' },
      { userAgent: 'anthropic-ai', disallow: '/' },
      { userAgent: 'Claude-Web',   disallow: '/' },
      { userAgent: 'Google-Extended', disallow: '/' },
      { userAgent: 'PerplexityBot',   disallow: '/' },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  }
}
