export const NIGERIAN_UNIVERSITY_DOMAINS: Record<string, string> = {
  'unilag.edu.ng': 'University of Lagos',
  'ui.edu.ng': 'University of Ibadan',
  'oauife.edu.ng': 'Obafemi Awolowo University',
  'unn.edu.ng': 'University of Nigeria, Nsukka',
  'abiastate.edu.ng': 'Abia State University',
  'aaua.edu.ng': 'Adekunle Ajasin University',
  'abuad.edu.ng': 'Afe Babalola University',
  'achievers.edu.ng': 'Achievers University',
  'adelekeuniversity.edu.ng': 'Adeleke University',
  'adsu.edu.ng': 'Adamawa State University',
  'aefunai.edu.ng': 'Alex Ekwueme Federal University',
  'afrihub.edu.ng': 'AfriHUB University',
  'afutech.edu.ng': 'Abubakar Tatari Ali Polytechnic',
  'aksu.edu.ng': 'Akwa Ibom State University',
  'aletheia.edu.ng': 'Aletheia University',
  'alustudent.com': 'African Leadership University',
  'aun.edu.ng': 'American University of Nigeria',
  'augustineuniversity.edu.ng': 'Augustine University',
  'babcock.edu.ng': 'Babcock University',
  'bazeuniversity.edu.ng': 'Baze University',
  'benu.edu.ng': 'Benue State University',
  'bsu.edu.ng': 'Bayero University Kano',
  'buk.edu.ng': 'Bayero University Kano',
  'caluniv.edu.ng': 'University of Calabar',
  'covenantuniversity.edu.ng': 'Covenant University',
  'crawford.edu.ng': 'Crawford University',
  'crsu.edu.ng': 'Cross River State University',
  'crutech.edu.ng': 'Cross River University of Technology',
  'cu.edu.ng': 'Covenant University',
  'delsu.edu.ng': 'Delta State University',
  'ebsu.edu.ng': 'Ebonyi State University',
  'eksu.edu.ng': 'Ekiti State University',
  'elizadeuniversity.edu.ng': 'Elizade University',
  'eru.edu.ng': 'Edwin Clark University',
  'esut.edu.ng': 'Enugu State University',
  'faua.edu.ng': 'Federal University of Agriculture, Abeokuta',
  'fubk.edu.ng': 'Federal University Birnin Kebbi',
  'fud.edu.ng': 'Federal University Dutse',
  'fudutsinma.edu.ng': 'Federal University Dutsinma',
  'fuhso.edu.ng': 'Federal University of Health Sciences',
  'fulafia.edu.ng': 'Federal University Lafia',
  'fulokoja.edu.ng': 'Federal University Lokoja',
  'funaab.edu.ng': 'Federal University of Agriculture, Abeokuta',
  'funai.edu.ng': 'Federal University Ndufu-Alike',
  'futo.edu.ng': 'Federal University of Technology, Owerri',
  'futminna.edu.ng': 'Federal University of Technology, Minna',
  'gsu.edu.ng': 'Gombe State University',
  'gul.edu.ng': 'Gregory University Uturu',
  'hallmarkuniversity.edu.ng': 'Hallmark University',
  'hubuniversity.edu.ng': 'Hub University',
  'ibbu.edu.ng': 'Ibrahim Badamasi Babangida University',
  'idu.edu.ng': 'Igbinedion University',
  'imsubis.edu.ng': 'Imo State University',
  'imsu.edu.ng': 'Imo State University',
  'jabu.edu.ng': 'Joseph Ayo Babalola University',
  'justiceuniversity.edu.ng': 'Justice University',
  'kasu.edu.ng': 'Kaduna State University',
  'kdu.edu.ng': 'Kings University',
  'kiu.edu.ng': 'Kogi State University',
  'knu.edu.ng': 'Kebbi State University',
  'kosutech.edu.ng': 'Kogi State University of Technology',
  'ksu.edu.ng': 'Katsina State University',
  'kwara.edu.ng': 'Kwara State University',
  'kwasu.edu.ng': 'Kwara State University',
  'lasu.edu.ng': 'Lagos State University',
  'lautech.edu.ng': 'Ladoke Akintola University of Technology',
  'lcu.edu.ng': 'Lead City University',
  'lmu.edu.ng': 'Landmark University',
  'madonna.edu.ng': 'Madonna University',
  'mapoly.edu.ng': 'Moshood Abiola Polytechnic',
  'mcuniversity.edu.ng': 'Michael and Cecilia Ibru University',
  'miva.edu.ng': 'MIVA University',
  'moua.edu.ng': 'Mountain Top University',
  'mountaintopu.edu.ng': 'Mountain Top University',
  'mtu.edu.ng': 'Mountain Top University',
  'nau.edu.ng': 'Nnamdi Azikiwe University',
  'nilds.gov.ng': 'National Institute for Legislative Studies',
  'noun.edu.ng': 'National Open University of Nigeria',
  'novenauniversity.edu.ng': 'Novena University',
  'nsuk.edu.ng': 'Nasarawa State University',
  'odu.edu.ng': 'Osun State University',
  'osun.edu.ng': 'Osun State University',
  'osutech.edu.ng': 'Osun State College of Technology',
  'oua.edu.ng': 'Olabisi Onabanjo University',
  'oye-ekiti.edu.ng': 'Federal University Oye-Ekiti',
  'plasu.edu.ng': 'Plateau State University',
  'portharcourt.edu.ng': 'University of Port Harcourt',
  'redeemer.edu.ng': "Redeemer's University",
  'run.edu.ng': "Redeemer's University",
  'ritman.edu.ng': 'Ritman University',
  'rsust.edu.ng': 'Rivers State University',
  'salem.edu.ng': 'Salem University',
  'spiritandlife.edu.ng': 'Spirit and Life University',
  'ssu.edu.ng': 'Sokoto State University',
  'stanslas.edu.ng': 'Stanislaus University',
  'tansianuniversity.edu.ng': 'Tansian University',
  'tasued.edu.ng': 'Tai Solarin University of Education',
  'tnu.edu.ng': 'Topfaith University',
  'tsu.edu.ng': 'Taraba State University',
  'unical.edu.ng': 'University of Calabar',
  'unilorin.edu.ng': 'University of Ilorin',
  'unimaid.edu.ng': 'University of Maiduguri',
  'uniport.edu.ng': 'University of Port Harcourt',
  'uniuyo.edu.ng': 'University of Uyo',
  'unizik.edu.ng': 'Nnamdi Azikiwe University',
  'usmanu.edu.ng': 'Usmanu Danfodiyo University',
  'veritas.edu.ng': 'Veritas University',
  'westernedelta.edu.ng': 'Western Delta University',
  'ysu.edu.ng': 'Yobe State University',
  'yusuf.edu.ng': 'Yusuf Maitama Sule University',
}

export function detectUniversity(email: string): string | null {
  const domain = email.split('@')[1]?.toLowerCase()
  if (!domain) return null
  return NIGERIAN_UNIVERSITY_DOMAINS[domain] ?? null
}

export function isUniversityEmail(email: string): boolean {
  return detectUniversity(email) !== null
}
